### ISSUE TITLE
About python version

### ISSUE THREAD

**Issue by yqdleiyi** [Alleinx/M3-IMPUTE#1]
Hello, I tried to install epipverything following the guidance, but it seems that python 3.11.6 is not available anymore in current conda and pip. Could you please check it? Thank you.

**Comment by Alleinx** [comment]
Hi yqdleiyi,

Many thanks for your interest in our project. You can try the latest version of Python 3.11 (3.11.11) and it should work fine.

**Comment by yqdleiyi** [comment]
Thank you. It's solved.
